In [4]:
import pandas as pd
import numpy as np

In [124]:
df=pd.read_excel('Netflix_Unclean_Project.xlsx')

In [8]:
df

,Customer_ID,Customer_Name,Age,Title,Content_Type,Genre,Country,Subscription_Plan,Device,Payment_Method,Account_Status,Join_Date,Last_Watch_Date,Watch_Hours,Monthly_Fee,Movies_Watched,Episodes_Watched,Avg_Rating,Monthly_Sessions,Download_Count
0,CUST10927,Customer 927,25,Bridgerton,TV Show,Drama,Japan,Premium,Gaming Console,PayPal,Active,2024-06-20,2024-12-21,28.0,649,5,97,3.6,11,3
1,CUST10631,Customer 631,38,Bridgerton,Movie,Documentary,Japan,Basic,Mobile,PayPal,Active,2024-01-01,2024-08-14,0.0,149,5,84,4.5,22,19
2,CUST10683,Customer 683,40,Money Heist,TV Show,Sci-Fi,France,Basic,Tablet,Debit Card,Paused,2024-11-18,2025-10-31,28.9,149,16,106,3.8,26,3
3,CUST10515,Customer 515,44,You,TV Show,Action,Spain,Premium,Gaming Console,Credit Card,Active,2023-02-21,2023-06-18,27.6,649,10,24,2.6,27,9
4,CUST10366,Customer 366,57,The Witcher,TV Show,Comedy,Canada,Premium,Smart TV,Credit Card,Active,2024-01-16,2025-06-09,32.0,649,10,78,3.2,15,20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1008,CUST55545,Customer 515,44,You,TV Show,Action,Spain,Premium,Gaming Console,Credit Card,Active,2023-02-21,2023-06-18,27.6,649,10,24,2.6,27,9
1009,CUST55546,Customer 366,57,The Witcher,TV Show,Comedy,Canada,Premium,Smart TV,Credit Card,Active,2024-01-16,2025-06-09,32.0,649,10,78,3.2,15,20
1010,CUST55547,Customer 656,42,You,Movie,NaN,Germany,Basic,Mobile,Credit Card,Paused,2023-10-31,2025-08-10,43.5,149,32,11,4.5,12,7
1011,CUST55548,Customer 657,22,Squid Game,TV Show,Documentary,Canada,Premium,Smart TV,Credit Card,Active,2025-05-15,2025-09-11,42.3,649,19,11,2.8,12,23
1012,CUST55549,Customer 530,61,Elite,Movie,Drama,Germany,Standard,Tablet,Debit Card,Paused,2025-04-08,2026-05-21,19.4,499,14,91,3.5,15,23

In [93]:
df.shape

(1013, 20)

In [12]:
df.isnull().sum()

Customer_ID          0
Customer_Name        0
Age                  0
Title                0
Content_Type         0
Genre                3
Country              0
Subscription_Plan    0
Device               4
Payment_Method       5
Account_Status       0
Join_Date            0
Last_Watch_Date      0
Watch_Hours          0
Monthly_Fee          0
Movies_Watched       0
Episodes_Watched     0
Avg_Rating           0
Monthly_Sessions     0
Download_Count       0
dtype: int64

In [17]:
df.duplicated().sum()

np.int64(0)

In [118]:
df.drop_duplicates(inplace=True)

In [119]:
df.replace(['NULL','N/A','',' '],np.nan,inplace=True)

,Customer_ID,Customer_Name,Age,Title,Content_Type,Genre,Country,Subscription_Plan,Device,Payment_Method,Account_Status,Join_Date,Last_Watch_Date,Watch_Hours,Monthly_Fee,Movies_Watched,Episodes_Watched,Avg_Rating,Monthly_Sessions,Download_Count
0,CUST10927,Customer 927,25,Bridgerton,TV Show,Drama,Japan,Premium,Gaming Console,PayPal,Active,2024-06-20,2024-12-21,28.0,649,5,97,3.6,11,3
1,CUST10631,Customer 631,38,Bridgerton,Movie,Documentary,Japan,Basic,Mobile,PayPal,Active,2024-01-01,2024-08-14,0.0,149,5,84,4.5,22,19
2,CUST10683,Customer 683,40,Money Heist,TV Show,Sci-Fi,France,Basic,Tablet,Debit Card,Paused,2024-11-18,2025-10-31,28.9,149,16,106,3.8,26,3
3,CUST10515,Customer 515,44,You,TV Show,Action,Spain,Premium,Gaming Console,Credit Card,Active,2023-02-21,2023-06-18,27.6,649,10,24,2.6,27,9
4,CUST10366,Customer 366,57,The Witcher,TV Show,Comedy,Canada,Premium,Smart TV,Credit Card,Active,2024-01-16,2025-06-09,32.0,649,10,78,3.2,15,20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1008,CUST55545,Customer 515,44,You,TV Show,Action,Spain,Premium,Gaming Console,Credit Card,Active,2023-02-21,2023-06-18,27.6,649,10,24,2.6,27,9
1009,CUST55546,Customer 366,57,The Witcher,TV Show,Comedy,Canada,Premium,Smart TV,Credit Card,Active,2024-01-16,2025-06-09,32.0,649,10,78,3.2,15,20
1010,CUST55547,Customer 656,42,You,Movie,NaN,Germany,Basic,Mobile,Credit Card,Paused,2023-10-31,2025-08-10,43.5,149,32,11,4.5,12,7
1011,CUST55548,Customer 657,22,Squid Game,TV Show,Documentary,Canada,Premium,Smart TV,Credit Card,Active,2025-05-15,2025-09-11,42.3,649,19,11,2.8,12,23
1012,CUST55549,Customer 530,61,Elite,Movie,Drama,Germany,Standard,Tablet,Debit Card,Paused,2025-04-08,2026-05-21,19.4,499,14,91,3.5,15,23

In [127]:
 df= df.apply(lambda x: x.str.strip()if x.dtype=='str' else x )

In [120]:
df.info()

<class 'pandas.DataFrame'>
Index: 1008 entries, 0 to 1012
Data columns (total 20 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Customer_ID        1008 non-null   str
 1   Customer_Name      1008 non-null   str
 2   Age                1008 non-null   int64
 3   Title              1008 non-null   str
 4   Content_Type       1008 non-null   str
 5   Genre              1004 non-null   str
 6   Country            1007 non-null   str
 7   Subscription_Plan  1008 non-null   str
 8   Device             1004 non-null   str
 9   Payment_Method     1001 non-null   str
 10  Account_Status     1008 non-null   str
 11  Join_Date          1008 non-null   datetime64[us]
 12  Last_Watch_Date    1008 non-null   datetime64[us]
 13  Watch_Hours        1008 non-null   float64
 14  Monthly_Fee        1008 non-null   int64
 15  Movies_Watched     1008 non-null   int64
 16  Episodes_Watched   1008 non-null   int64
 17  Avg_Rating         1008 non-null   float64
 18  Monthly_Sessions   1008 non-null   int64
 19  Download_Count     1008 non-null   int64
dtypes: datetime64[us](2), float64(2), int64(6), str(10)
memory usage: 165.4 KB

In [126]:
df['Country']= df['Country'].str.title()
df['Customer_Name']= df['Customer_Name'].str.title()
df['Title']= df['Title'].str.title()
df['Genre']= df['Genre'].str.title()
df['Device']= df['Device'].str.title()
df['Payment_Method']= df['Payment_Method'].str.title()
df['Subscription_Plan']= df['Subscription_Plan'].str.title()
df['Account_Status']= df['Account_Status'].str.title()

In [122]:
df

,Customer_ID,Customer_Name,Age,Title,Content_Type,Genre,Country,Subscription_Plan,Device,Payment_Method,Account_Status,Join_Date,Last_Watch_Date,Watch_Hours,Monthly_Fee,Movies_Watched,Episodes_Watched,Avg_Rating,Monthly_Sessions,Download_Count
0,CUST10927,Customer 927,25,Bridgerton,TV Show,Drama,Japan,Premium,Gaming Console,Paypal,Active,2024-06-20,2024-12-21,28.0,649,5,97,3.6,11,3
1,CUST10631,Customer 631,38,Bridgerton,Movie,Documentary,Japan,Basic,Mobile,Paypal,Active,2024-01-01,2024-08-14,0.0,149,5,84,4.5,22,19
2,CUST10683,Customer 683,40,Money Heist,TV Show,Sci-Fi,France,Basic,Tablet,Debit Card,Paused,2024-11-18,2025-10-31,28.9,149,16,106,3.8,26,3
3,CUST10515,Customer 515,44,You,TV Show,Action,Spain,Premium,Gaming Console,Credit Card,Active,2023-02-21,2023-06-18,27.6,649,10,24,2.6,27,9
4,CUST10366,Customer 366,57,The Witcher,TV Show,Comedy,Canada,Premium,Smart Tv,Credit Card,Active,2024-01-16,2025-06-09,32.0,649,10,78,3.2,15,20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1008,CUST55545,Customer 515,44,You,TV Show,Action,Spain,Premium,Gaming Console,Credit Card,Active,2023-02-21,2023-06-18,27.6,649,10,24,2.6,27,9
1009,CUST55546,Customer 366,57,The Witcher,TV Show,Comedy,Canada,Premium,Smart Tv,Credit Card,Active,2024-01-16,2025-06-09,32.0,649,10,78,3.2,15,20
1010,CUST55547,Customer 656,42,You,Movie,NaN,Germany,Basic,Mobile,Credit Card,Paused,2023-10-31,2025-08-10,43.5,149,32,11,4.5,12,7
1011,CUST55548,Customer 657,22,Squid Game,TV Show,Documentary,Canada,Premium,Smart Tv,Credit Card,Active,2025-05-15,2025-09-11,42.3,649,19,11,2.8,12,23
1012,CUST55549,Customer 530,61,Elite,Movie,Drama,Germany,Standard,Tablet,Debit Card,Paused,2025-04-08,2026-05-21,19.4,499,14,91,3.5,15,23

In [41]:
df['Country'].value_counts()

Country
Spain             109
United States     107
Germany           104
Canada            103
United Kingdom    102
Japan             100
France             98
India              97
South Korea        96
Australia          91
Name: count, dtype: int64

In [128]:
df.describe()

,Age,Join_Date,Last_Watch_Date,Watch_Hours,Monthly_Fee,Movies_Watched,Episodes_Watched,Avg_Rating,Monthly_Sessions,Download_Count
count,1013.000000,1013,1013,1013.000000,1013.000000,1013.000000,1013.000000,1013.000000,1013.000000,1013.000000
mean,42.063179,2023-12-16 10:21:12.260612,2024-11-27 19:59:45.784797,42.417473,436.222113,18.187562,59.834156,3.752419,16.686081,12.472853
min,-10.000000,2022-01-01 00:00:00,2022-01-21 00:00:00,-20.000000,-649.000000,1.000000,0.000000,2.500000,2.000000,0.000000
25%,30.000000,2022-12-08 00:00:00,2023-12-26 00:00:00,25.700000,149.000000,9.000000,31.000000,3.100000,10.000000,6.000000
50%,43.000000,2023-12-29 00:00:00,2024-12-03 00:00:00,42.300000,499.000000,18.000000,59.000000,3.700000,17.000000,12.000000
75%,53.000000,2024-12-13 00:00:00,2025-11-14 00:00:00,58.100000,649.000000,27.000000,91.000000,4.400000,24.000000,19.000000
max,200.000000,2025-11-01 00:00:00,2027-08-18 00:00:00,138.300000,649.000000,35.000000,120.000000,5.000000,30.000000,25.000000
std,15.245811,NaN,NaN,23.988529,214.348252,10.123758,34.895300,0.722812,8.290083,7.577303

In [129]:
df=df[(df['Age']>=18) & (df['Age']<=100)]

In [65]:
df['Age'].describe()

count    1013.000000
mean       42.063179
std        15.245811
min       -10.000000
25%        30.000000
50%        43.000000
75%        53.000000
max       200.000000
Name: Age, dtype: float64

In [56]:
df=df['Watch_Hours']>=0

In [61]:
df.describe

<bound method NDFrame.describe of 0       True
1       True
2       True
3       True
4       True
        ...
1008    True
1009    True
1010    True
1011    True
1012    True
Name: Watch_Hours, Length: 1003, dtype: bool>

In [66]:
df

,Customer_ID,Customer_Name,Age,Title,Content_Type,Genre,Country,Subscription_Plan,Device,Payment_Method,Account_Status,Join_Date,Last_Watch_Date,Watch_Hours,Monthly_Fee,Movies_Watched,Episodes_Watched,Avg_Rating,Monthly_Sessions,Download_Count
0,CUST10927,Customer 927,25,Bridgerton,TV Show,Drama,Japan,Premium,Gaming Console,PayPal,Active,2024-06-20,2024-12-21,28.0,649,5,97,3.6,11,3
1,CUST10631,Customer 631,38,Bridgerton,Movie,Documentary,Japan,Basic,Mobile,PayPal,Active,2024-01-01,2024-08-14,0.0,149,5,84,4.5,22,19
2,CUST10683,Customer 683,40,Money Heist,TV Show,Sci-Fi,France,Basic,Tablet,Debit Card,Paused,2024-11-18,2025-10-31,28.9,149,16,106,3.8,26,3
3,CUST10515,Customer 515,44,You,TV Show,Action,Spain,Premium,Gaming Console,Credit Card,Active,2023-02-21,2023-06-18,27.6,649,10,24,2.6,27,9
4,CUST10366,Customer 366,57,The Witcher,TV Show,Comedy,Canada,Premium,Smart TV,Credit Card,Active,2024-01-16,2025-06-09,32.0,649,10,78,3.2,15,20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1008,CUST55545,Customer 515,44,You,TV Show,Action,Spain,Premium,Gaming Console,Credit Card,Active,2023-02-21,2023-06-18,27.6,649,10,24,2.6,27,9
1009,CUST55546,Customer 366,57,The Witcher,TV Show,Comedy,Canada,Premium,Smart TV,Credit Card,Active,2024-01-16,2025-06-09,32.0,649,10,78,3.2,15,20
1010,CUST55547,Customer 656,42,You,Movie,NaN,Germany,Basic,Mobile,Credit Card,Paused,2023-10-31,2025-08-10,43.5,149,32,11,4.5,12,7
1011,CUST55548,Customer 657,22,Squid Game,TV Show,Documentary,Canada,Premium,Smart TV,Credit Card,Active,2025-05-15,2025-09-11,42.3,649,19,11,2.8,12,23
1012,CUST55549,Customer 530,61,Elite,Movie,Drama,Germany,Standard,Tablet,Debit Card,Paused,2025-04-08,2026-05-21,19.4,499,14,91,3.5,15,23

In [68]:
df.head()

,Customer_ID,Customer_Name,Age,Title,Content_Type,Genre,Country,Subscription_Plan,Device,Payment_Method,Account_Status,Join_Date,Last_Watch_Date,Watch_Hours,Monthly_Fee,Movies_Watched,Episodes_Watched,Avg_Rating,Monthly_Sessions,Download_Count
0,CUST10927,Customer 927,25,Bridgerton,TV Show,Drama,Japan,Premium,Gaming Console,PayPal,Active,2024-06-20,2024-12-21,28.0,649,5,97,3.6,11,3
1,CUST10631,Customer 631,38,Bridgerton,Movie,Documentary,Japan,Basic,Mobile,PayPal,Active,2024-01-01,2024-08-14,0.0,149,5,84,4.5,22,19
2,CUST10683,Customer 683,40,Money Heist,TV Show,Sci-Fi,France,Basic,Tablet,Debit Card,Paused,2024-11-18,2025-10-31,28.9,149,16,106,3.8,26,3
3,CUST10515,Customer 515,44,You,TV Show,Action,Spain,Premium,Gaming Console,Credit Card,Active,2023-02-21,2023-06-18,27.6,649,10,24,2.6,27,9
4,CUST10366,Customer 366,57,The Witcher,TV Show,Comedy,Canada,Premium,Smart TV,Credit Card,Active,2024-01-16,2025-06-09,32.0,649,10,78,3.2,15,20

In [130]:
df.describe()

,Age,Join_Date,Last_Watch_Date,Watch_Hours,Monthly_Fee,Movies_Watched,Episodes_Watched,Avg_Rating,Monthly_Sessions,Download_Count
count,1008.000000,1008,1008,1008.000000,1008.000000,1008.000000,1008.000000,1008.000000,1008.000000,1008.000000
mean,41.939484,2023-12-15 21:07:08.571428,2024-11-26 18:54:17.142857,42.359821,436.803571,18.203373,59.791667,3.751786,16.669643,12.474206
min,18.000000,2022-01-01 00:00:00,2022-01-21 00:00:00,-20.000000,-649.000000,1.000000,0.000000,2.500000,2.000000,0.000000
25%,30.000000,2022-12-07 18:00:00,2023-12-25 12:00:00,25.475000,149.000000,9.000000,30.750000,3.100000,10.000000,6.000000
50%,43.000000,2023-12-28 12:00:00,2024-12-02 12:00:00,42.300000,499.000000,18.000000,59.000000,3.700000,17.000000,12.000000
75%,53.000000,2024-12-11 12:00:00,2025-11-13 06:00:00,58.025000,649.000000,27.000000,90.250000,4.400000,24.000000,19.000000
max,65.000000,2025-11-01 00:00:00,2027-08-18 00:00:00,138.300000,649.000000,35.000000,120.000000,5.000000,30.000000,25.000000
std,13.805260,NaN,NaN,23.988269,214.192252,10.117449,34.870426,0.721920,8.288552,7.577427

In [70]:
df=df[(df['Age']>=18) & (df['Age']<=100)]

In [85]:
df

,Customer_ID,Customer_Name,Age,Title,Content_Type,Genre,Country,Subscription_Plan,Device,Payment_Method,Account_Status,Join_Date,Last_Watch_Date,Watch_Hours,Monthly_Fee,Movies_Watched,Episodes_Watched,Avg_Rating,Monthly_Sessions,Download_Count
17,CUST10980,Customer 980,63,Peaky Blinders,Movie,Sci-Fi,Spain,Basic,Gaming Console,UPI,Active,2023-12-15,2025-03-08,61.0,-649,32,75,3.6,7,0
379,CUST10074,Customer 74,58,Wednesday,Movie,Crime,Germany,Premium,Mobile,Net Banking,Active,2022-10-08,2023-02-20,81.1,-149,6,116,3.2,25,13
515,CUST10634,Customer 634,63,Stranger Things,Movie,Drama,Australia,Premium,Mobile,Debit Card,Active,2025-04-18,2026-07-01,31.3,-499,16,79,2.7,6,11

In [99]:
df=df[df['Watch_Hours']>=0]

In [145]:
df['Age']=df['Age'].fillna(df['Age'].mean())
df['Watch_Hours']=df['Watch_Hours'].fillna(df['Watch_Hours'].mean())
df['Monthly_Fee']=df['Monthly_Fee'].fillna(df['Monthly_Fee'].mean())

In [148]:
df['Payment_Method']=df['Payment_Method'].fillna('Unknown')
df['Device']=df['Device'].fillna('Unknown')
df['Genre']=df['Genre'].fillna('Unknown')

In [139]:
df

,Customer_ID,Customer_Name,Age,Title,Content_Type,Genre,Country,Subscription_Plan,Device,Payment_Method,Account_Status,Join_Date,Last_Watch_Date,Watch_Hours,Monthly_Fee,Movies_Watched,Episodes_Watched,Avg_Rating,Monthly_Sessions,Download_Count
0,CUST10927,Customer 927,25,Bridgerton,TV Show,Drama,Japan,Premium,Gaming Console,Paypal,Active,2024-06-20,2024-12-21,28.0,649,5,97,3.6,11,3
1,CUST10631,Customer 631,38,Bridgerton,Movie,Documentary,Japan,Basic,Mobile,Paypal,Active,2024-01-01,2024-08-14,0.0,149,5,84,4.5,22,19
2,CUST10683,Customer 683,40,Money Heist,TV Show,Sci-Fi,France,Basic,Tablet,Debit Card,Paused,2024-11-18,2025-10-31,28.9,149,16,106,3.8,26,3
3,CUST10515,Customer 515,44,You,TV Show,Action,Spain,Premium,Gaming Console,Credit Card,Active,2023-02-21,2023-06-18,27.6,649,10,24,2.6,27,9
4,CUST10366,Customer 366,57,The Witcher,TV Show,Comedy,Canada,Premium,Smart Tv,Credit Card,Active,2024-01-16,2025-06-09,32.0,649,10,78,3.2,15,20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1008,CUST55545,Customer 515,44,You,TV Show,Action,Spain,Premium,Gaming Console,Credit Card,Active,2023-02-21,2023-06-18,27.6,649,10,24,2.6,27,9
1009,CUST55546,Customer 366,57,The Witcher,TV Show,Comedy,Canada,Premium,Smart Tv,Credit Card,Active,2024-01-16,2025-06-09,32.0,649,10,78,3.2,15,20
1010,CUST55547,Customer 656,42,You,Movie,NaN,Germany,Basic,Mobile,Credit Card,Paused,2023-10-31,2025-08-10,43.5,149,32,11,4.5,12,7
1011,CUST55548,Customer 657,22,Squid Game,TV Show,Documentary,Canada,Premium,Smart Tv,Credit Card,Active,2025-05-15,2025-09-11,42.3,649,19,11,2.8,12,23
1012,CUST55549,Customer 530,61,Elite,Movie,Drama,Germany,Standard,Tablet,Debit Card,Paused,2025-04-08,2026-05-21,19.4,499,14,91,3.5,15,23

In [106]:
df.head()

,Customer_ID,Customer_Name,Age,Title,Content_Type,Genre,Country,Subscription_Plan,Device,Payment_Method,Account_Status,Join_Date,Last_Watch_Date,Watch_Hours,Monthly_Fee,Movies_Watched,Episodes_Watched,Avg_Rating,Monthly_Sessions,Download_Count
17,CUST10980,Customer 980,63,Peaky Blinders,Movie,Sci-Fi,Spain,Basic,Gaming Console,Upi,Active,2023-12-15,2025-03-08,61.0,-649,32,75,3.6,7,0
379,CUST10074,Customer 74,58,Wednesday,Movie,Crime,Germany,Premium,Mobile,Net Banking,Active,2022-10-08,2023-02-20,81.1,-149,6,116,3.2,25,13
515,CUST10634,Customer 634,63,Stranger Things,Movie,Drama,Australia,Premium,Mobile,Debit Card,Active,2025-04-18,2026-07-01,31.3,-499,16,79,2.7,6,11

In [114]:
df.describe()

,Age,Join_Date,Last_Watch_Date,Watch_Hours,Monthly_Fee,Movies_Watched,Episodes_Watched,Avg_Rating,Monthly_Sessions,Download_Count
count,0.0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
mean,NaN,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [113]:
df

Empty DataFrame
Columns: [Customer_ID, Customer_Name, Age, Title, Content_Type, Genre, Country, Subscription_Plan, Device, Payment_Method, Account_Status, Join_Date, Last_Watch_Date, Watch_Hours, Monthly_Fee, Movies_Watched, Episodes_Watched, Avg_Rating, Monthly_Sessions, Download_Count]
Index: []

In [136]:
df

,Customer_ID,Customer_Name,Age,Title,Content_Type,Genre,Country,Subscription_Plan,Device,Payment_Method,Account_Status,Join_Date,Last_Watch_Date,Watch_Hours,Monthly_Fee,Movies_Watched,Episodes_Watched,Avg_Rating,Monthly_Sessions,Download_Count
0,CUST10927,Customer 927,25,Bridgerton,TV Show,Drama,Japan,Premium,Gaming Console,Paypal,Active,2024-06-20,2024-12-21,28.0,649,5,97,3.6,11,3
1,CUST10631,Customer 631,38,Bridgerton,Movie,Documentary,Japan,Basic,Mobile,Paypal,Active,2024-01-01,2024-08-14,0.0,149,5,84,4.5,22,19
2,CUST10683,Customer 683,40,Money Heist,TV Show,Sci-Fi,France,Basic,Tablet,Debit Card,Paused,2024-11-18,2025-10-31,28.9,149,16,106,3.8,26,3
3,CUST10515,Customer 515,44,You,TV Show,Action,Spain,Premium,Gaming Console,Credit Card,Active,2023-02-21,2023-06-18,27.6,649,10,24,2.6,27,9
4,CUST10366,Customer 366,57,The Witcher,TV Show,Comedy,Canada,Premium,Smart Tv,Credit Card,Active,2024-01-16,2025-06-09,32.0,649,10,78,3.2,15,20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1008,CUST55545,Customer 515,44,You,TV Show,Action,Spain,Premium,Gaming Console,Credit Card,Active,2023-02-21,2023-06-18,27.6,649,10,24,2.6,27,9
1009,CUST55546,Customer 366,57,The Witcher,TV Show,Comedy,Canada,Premium,Smart Tv,Credit Card,Active,2024-01-16,2025-06-09,32.0,649,10,78,3.2,15,20
1010,CUST55547,Customer 656,42,You,Movie,NaN,Germany,Basic,Mobile,Credit Card,Paused,2023-10-31,2025-08-10,43.5,149,32,11,4.5,12,7
1011,CUST55548,Customer 657,22,Squid Game,TV Show,Documentary,Canada,Premium,Smart Tv,Credit Card,Active,2025-05-15,2025-09-11,42.3,649,19,11,2.8,12,23
1012,CUST55549,Customer 530,61,Elite,Movie,Drama,Germany,Standard,Tablet,Debit Card,Paused,2025-04-08,2026-05-21,19.4,499,14,91,3.5,15,23

In [135]:
df=df[df['Watch_Hours']>=0]
df= df[df['Monthly_Fee']>=0]

In [138]:
df.describe()

,Age,Join_Date,Last_Watch_Date,Watch_Hours,Monthly_Fee,Movies_Watched,Episodes_Watched,Avg_Rating,Monthly_Sessions,Download_Count
count,1000.000000,1000,1000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.0000
mean,41.887000,2023-12-16 18:14:24,2024-11-27 09:31:40.800000,42.572300,438.650000,18.178000,59.584000,3.755000,16.697000,12.4850
min,18.000000,2022-01-01 00:00:00,2022-01-21 00:00:00,0.000000,149.000000,1.000000,0.000000,2.500000,2.000000,0.0000
25%,30.000000,2022-12-09 00:00:00,2023-12-26 00:00:00,25.700000,149.000000,9.000000,30.000000,3.100000,10.000000,6.0000
50%,43.000000,2023-12-29 00:00:00,2024-12-02 12:00:00,42.400000,499.000000,18.000000,58.000000,3.700000,17.000000,12.0000
75%,53.000000,2024-12-09 12:00:00,2025-11-11 12:00:00,58.025000,649.000000,27.000000,90.000000,4.400000,24.000000,19.0000
max,65.000000,2025-11-01 00:00:00,2027-08-18 00:00:00,138.300000,649.000000,35.000000,120.000000,5.000000,30.000000,25.0000
std,13.790882,NaN,NaN,23.757593,209.043241,10.110516,34.835046,0.722604,8.283466,7.5823

In [142]:
df

,Customer_ID,Customer_Name,Age,Title,Content_Type,Genre,Country,Subscription_Plan,Device,Payment_Method,Account_Status,Join_Date,Last_Watch_Date,Watch_Hours,Monthly_Fee,Movies_Watched,Episodes_Watched,Avg_Rating,Monthly_Sessions,Download_Count
0,CUST10927,Customer 927,25,Bridgerton,TV Show,Drama,Japan,Premium,Gaming Console,Paypal,Active,2024-06-20,2024-12-21,28.0,649,5,97,3.6,11,3
1,CUST10631,Customer 631,38,Bridgerton,Movie,Documentary,Japan,Basic,Mobile,Paypal,Active,2024-01-01,2024-08-14,0.0,149,5,84,4.5,22,19
2,CUST10683,Customer 683,40,Money Heist,TV Show,Sci-Fi,France,Basic,Tablet,Debit Card,Paused,2024-11-18,2025-10-31,28.9,149,16,106,3.8,26,3
3,CUST10515,Customer 515,44,You,TV Show,Action,Spain,Premium,Gaming Console,Credit Card,Active,2023-02-21,2023-06-18,27.6,649,10,24,2.6,27,9
4,CUST10366,Customer 366,57,The Witcher,TV Show,Comedy,Canada,Premium,Smart Tv,Credit Card,Active,2024-01-16,2025-06-09,32.0,649,10,78,3.2,15,20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1008,CUST55545,Customer 515,44,You,TV Show,Action,Spain,Premium,Gaming Console,Credit Card,Active,2023-02-21,2023-06-18,27.6,649,10,24,2.6,27,9
1009,CUST55546,Customer 366,57,The Witcher,TV Show,Comedy,Canada,Premium,Smart Tv,Credit Card,Active,2024-01-16,2025-06-09,32.0,649,10,78,3.2,15,20
1010,CUST55547,Customer 656,42,You,Movie,NaN,Germany,Basic,Mobile,Credit Card,Paused,2023-10-31,2025-08-10,43.5,149,32,11,4.5,12,7
1011,CUST55548,Customer 657,22,Squid Game,TV Show,Documentary,Canada,Premium,Smart Tv,Credit Card,Active,2025-05-15,2025-09-11,42.3,649,19,11,2.8,12,23
1012,CUST55549,Customer 530,61,Elite,Movie,Drama,Germany,Standard,Tablet,Debit Card,Paused,2025-04-08,2026-05-21,19.4,499,14,91,3.5,15,23

In [143]:
df.info()

<class 'pandas.DataFrame'>
Index: 1000 entries, 0 to 1012
Data columns (total 20 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Customer_ID        1000 non-null   str
 1   Customer_Name      1000 non-null   str
 2   Age                1000 non-null   int64
 3   Title              1000 non-null   str
 4   Content_Type       1000 non-null   str
 5   Genre              997 non-null    str
 6   Country            1000 non-null   str
 7   Subscription_Plan  1000 non-null   str
 8   Device             996 non-null    str
 9   Payment_Method     995 non-null    str
 10  Account_Status     1000 non-null   str
 11  Join_Date          1000 non-null   datetime64[us]
 12  Last_Watch_Date    1000 non-null   datetime64[us]
 13  Watch_Hours        1000 non-null   float64
 14  Monthly_Fee        1000 non-null   int64
 15  Movies_Watched     1000 non-null   int64
 16  Episodes_Watched   1000 non-null   int64
 17  Avg_Rating         1000 non-null   float64
 18  Monthly_Sessions   1000 non-null   int64
 19  Download_Count     1000 non-null   int64
dtypes: datetime64[us](2), float64(2), int64(6), str(10)
memory usage: 164.1 KB

In [146]:
df.isnull().sum()

Customer_ID          0
Customer_Name        0
Age                  0
Title                0
Content_Type         0
Genre                3
Country              0
Subscription_Plan    0
Device               4
Payment_Method       5
Account_Status       0
Join_Date            0
Last_Watch_Date      0
Watch_Hours          0
Monthly_Fee          0
Movies_Watched       0
Episodes_Watched     0
Avg_Rating           0
Monthly_Sessions     0
Download_Count       0
dtype: int64

In [149]:
df

,Customer_ID,Customer_Name,Age,Title,Content_Type,Genre,Country,Subscription_Plan,Device,Payment_Method,Account_Status,Join_Date,Last_Watch_Date,Watch_Hours,Monthly_Fee,Movies_Watched,Episodes_Watched,Avg_Rating,Monthly_Sessions,Download_Count
0,CUST10927,Customer 927,25,Bridgerton,TV Show,Drama,Japan,Premium,Gaming Console,Paypal,Active,2024-06-20,2024-12-21,28.0,649,5,97,3.6,11,3
1,CUST10631,Customer 631,38,Bridgerton,Movie,Documentary,Japan,Basic,Mobile,Paypal,Active,2024-01-01,2024-08-14,0.0,149,5,84,4.5,22,19
2,CUST10683,Customer 683,40,Money Heist,TV Show,Sci-Fi,France,Basic,Tablet,Debit Card,Paused,2024-11-18,2025-10-31,28.9,149,16,106,3.8,26,3
3,CUST10515,Customer 515,44,You,TV Show,Action,Spain,Premium,Gaming Console,Credit Card,Active,2023-02-21,2023-06-18,27.6,649,10,24,2.6,27,9
4,CUST10366,Customer 366,57,The Witcher,TV Show,Comedy,Canada,Premium,Smart Tv,Credit Card,Active,2024-01-16,2025-06-09,32.0,649,10,78,3.2,15,20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1008,CUST55545,Customer 515,44,You,TV Show,Action,Spain,Premium,Gaming Console,Credit Card,Active,2023-02-21,2023-06-18,27.6,649,10,24,2.6,27,9
1009,CUST55546,Customer 366,57,The Witcher,TV Show,Comedy,Canada,Premium,Smart Tv,Credit Card,Active,2024-01-16,2025-06-09,32.0,649,10,78,3.2,15,20
1010,CUST55547,Customer 656,42,You,Movie,Unknown,Germany,Basic,Mobile,Credit Card,Paused,2023-10-31,2025-08-10,43.5,149,32,11,4.5,12,7
1011,CUST55548,Customer 657,22,Squid Game,TV Show,Documentary,Canada,Premium,Smart Tv,Credit Card,Active,2025-05-15,2025-09-11,42.3,649,19,11,2.8,12,23
1012,CUST55549,Customer 530,61,Elite,Movie,Drama,Germany,Standard,Tablet,Debit Card,Paused,2025-04-08,2026-05-21,19.4,499,14,91,3.5,15,23

In [150]:
df['Costmer_revenue']=df['Monthly_Sessions']*df['Monthly_Fee']

In [152]:
df['Engagement_Score']=df['Watch_Hours'] +df['Monthly_Sessions']+ df['Download_Count']

In [153]:
df.head(1)

,Customer_ID,Customer_Name,Age,Title,Content_Type,Genre,Country,Subscription_Plan,Device,Payment_Method,...,Last_Watch_Date,Watch_Hours,Monthly_Fee,Movies_Watched,Episodes_Watched,Avg_Rating,Monthly_Sessions,Download_Count,Costmer_revenue,Engagement_Score
0,CUST10927,Customer 927,25,Bridgerton,TV Show,Drama,Japan,Premium,Gaming Console,Paypal,...,2024-12-21,28.0,649,5,97,3.6,11,3,7139,42.0

In [166]:
bins = [0,20,50,100,np.inf]
label = ['low','medium','high','super_high']

df['Watch_Category']= pd.cut(df['Watch_Hours'],bins=bins,labels=label
                            )

In [175]:
bins=[17,25,35,50,100]
label=['child','young','young+','55+']
df['Costmer_Age_Group']= pd.cut(df['Age'],bins=bins,labels=label)

In [176]:
df['Costmer_Age_Group'].value_counts()

Costmer_Age_Group
55+       326
young+    310
young     216
child     148
Name: count, dtype: int64

In [193]:
df['Active_AC']=np.where(df['Account_Status']=='Active',1,0)

In [200]:
df.isnull().sum()

Customer_ID           0
Customer_Name         0
Age                   0
Title                 0
Content_Type          0
Genre                 0
Country               0
Subscription_Plan     0
Device                0
Payment_Method        0
Account_Status        0
Join_Date             0
Last_Watch_Date       0
Watch_Hours           0
Monthly_Fee           0
Movies_Watched        0
Episodes_Watched      0
Avg_Rating            0
Monthly_Sessions      0
Download_Count        0
Costmer_revenue       0
Engagement_Score      0
Watch_Category       37
Costmer_Age_Group     0
Active_AC             0
dtype: int64

In [184]:
df.duplicated().sum()

np.int64(5)

In [182]:
df.drop_duplicates()

,Customer_ID,Customer_Name,Age,Title,Content_Type,Genre,Country,Subscription_Plan,Device,Payment_Method,...,Movies_Watched,Episodes_Watched,Avg_Rating,Monthly_Sessions,Download_Count,Costmer_revenue,Engagement_Score,Watch_Category,Costmer_Age_Group,Active_A/C
0,CUST10927,Customer 927,25,Bridgerton,TV Show,Drama,Japan,Premium,Gaming Console,Paypal,...,5,97,3.6,11,3,7139,42.0,medium,child,1
1,CUST10631,Customer 631,38,Bridgerton,Movie,Documentary,Japan,Basic,Mobile,Paypal,...,5,84,4.5,22,19,3278,41.0,NaN,young+,1
2,CUST10683,Customer 683,40,Money Heist,TV Show,Sci-Fi,France,Basic,Tablet,Debit Card,...,16,106,3.8,26,3,3874,57.9,medium,young+,0
3,CUST10515,Customer 515,44,You,TV Show,Action,Spain,Premium,Gaming Console,Credit Card,...,10,24,2.6,27,9,17523,63.6,medium,young+,1
4,CUST10366,Customer 366,57,The Witcher,TV Show,Comedy,Canada,Premium,Smart Tv,Credit Card,...,10,78,3.2,15,20,9735,67.0,medium,55+,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1008,CUST55545,Customer 515,44,You,TV Show,Action,Spain,Premium,Gaming Console,Credit Card,...,10,24,2.6,27,9,17523,63.6,medium,young+,1
1009,CUST55546,Customer 366,57,The Witcher,TV Show,Comedy,Canada,Premium,Smart Tv,Credit Card,...,10,78,3.2,15,20,9735,67.0,medium,55+,1
1010,CUST55547,Customer 656,42,You,Movie,Unknown,Germany,Basic,Mobile,Credit Card,...,32,11,4.5,12,7,1788,62.5,medium,young+,0
1011,CUST55548,Customer 657,22,Squid Game,TV Show,Documentary,Canada,Premium,Smart Tv,Credit Card,...,19,11,2.8,12,23,7788,77.3,medium,child,1
1012,CUST55549,Customer 530,61,Elite,Movie,Drama,Germany,Standard,Tablet,Debit Card,...,14,91,3.5,15,23,7485,57.4,low,55+,0

In [185]:
df.duplicated().sum()

np.int64(5)

In [186]:
df.to_csv('clean_netflix_data.csv',index=False)

In [187]:
from  sqlalchemy import create_engine

In [201]:
engine= create_engine('mysql+pymysql:root//Akash123/localhost/netflix_db')

ArgumentError: Could not parse SQLAlchemy URL from given URL string

In [199]:
df.drop(columns=['Active_A/C'],inplace=True)

In [203]:
engine = create_engine('mysql+pymysql://root:Akash123@localhost/netflix_db')

In [206]:
df.to_sql('Netflix_customers',con=engine ,index=False)

ValueError: Table 'Netflix_customers' already exists.